#mongo:
#  image: mongo
#  container_name: mongo
#  ports:
#    - 27017:27017
frontend:
  build: ../site/
  container_name: site
  env_file: env
  ports:
  - 3000:3000
greet:
  build: ../services/greet/
  container_name: greetService
  env_file: env
  ports:
  - 9001:9001
number:
  build: ../services/number/
  container_name: numberService
  env_file: env
  ports:
  - 9002:9002
user:
  build: ../services/user/
  container_name: userService
  env_file: env
  ports:
  - 9003:9003